---
title: "Homework 1"
author: Julian Ponce
output: github_document
---

This is my solution to HW1 

```{r}
library (tidyverse)
```

## Problem 1

Create a data frame with the specific elements

```{r create_df}
prob1_df = tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
  )
prob1_df
```


 Take the mean of each variable in my data frame. 

```{r mean_pull_var}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

Take mean of numbers 

```{r}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

## Problem 2

install.packages("palmerpenguins")


```{r}
data("penguins", package = "palmerpenguins")
mean(pull(penguins,flipper_length_mm), na.rm = TRUE)

```

```{r}
variable.names(penguins)
nrow(penguins)
ncol(penguins)
```


```{r}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm)) + geom_point(aes(color = species))

ggsave("penguins_scatter_plot.pdf")

```







```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

